steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/tegola-api-cloud-run/cicd-test:$COMMIT_SHA', '.' ]  
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#     # - 'gcloud'
#     - 'builds'
#     - 'submit'
#     - '--config' 
#     - './cloudbuild.yaml'
- name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cicd-test:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
  args:  
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'europe-west1-docker.pkg.dev/tegola-api-cloud-run/cicd-test:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'europe-west1-docker.pkg.dev/tegola-api-cloud-run/cicd-test:$COMMIT_SHA'
